_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehicles.urls')),
    path('users/', include('users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('detail/me/', views.Detail.as_view(), name='detail'),
    path('update/me/', views.Update.as_view(), name='update'),
    path('update/password/', views.UpdatePassword.as_view(), name='update_password'),
    path('forgot-password/', views.ForgotPassword.as_view(), name='forgot_password')
]

users/models.py
from django.db import models

# Create your models here.

users/forms/forgot_password_form.py
from django import forms
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput({
            'placeholder': 'Type your email here',
            'class': 'form-control'
        })
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            validate_email(email)
        except ValidationError:
            raise ValidationError('Invalid Email', code='invalid')
        else:
            return email

users/forms/login_form.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'form-control'
            }
        )
    )

users/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from users.utils.form_utils import *


class RegisterForm(forms.ModelForm):
    first_name = forms.CharField(
        label='First Name',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'First Name',
                'class': 'form-control'
            }
        )
    )

    last_name = forms.CharField(
        label='Last Name',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Last Name',
                'class': 'form-control'
            }
        )
    )

    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'form-control'
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email@example.com',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'form-control'
            }
        )
    )

    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirm Password',
                'class': 'form-control'
            }
        )
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        required_length = 6
        if len(username) < required_length:
            raise ValidationError(f'Username must have at least {required_length} characters', code='min_length')
        return username

    def clean_password(self):
        password = str(self.cleaned_data.get('password'))
        return validate_password(password)

    def clean(self):
        cleaned_data = super().clean()
        pw = cleaned_data.get('password')
        pw2 = cleaned_data.get('password2')
        return compare_passwords(pw, pw2)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

users/forms/update_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from users.utils.form_utils import *
from django.core.validators import validate_email


class UpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        label='First Name',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'First Name',
                'class': 'form-control'
            }
        )
    )

    last_name = forms.CharField(
        label='Last Name',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Last Name',
                'class': 'form-control'
            }
        )
    )

    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'form-control'
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email@example.com',
                'class': 'form-control'
            }
        )
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        required_length = 6
        if len(username) < required_length:
            raise ValidationError(f'Username must have at least {required_length} characters', code='min_length')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            validate_email(email)
        except ValidationError:
            raise ValidationError('Invalid Email')
        else:
            return email

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

users/forms/update_password_form.py
from django import forms
from users.utils.form_utils import *


class UpdatePasswordForm(forms.Form):
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'form-control'
            }
        )
    )

    new_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'New Password',
                'class': 'form-control'
            }
        )
    )

    new_password_confirm = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirm New Password',
                'class': 'form-control'
            }
        )
    )

    def clean(self):
        password = self.cleaned_data.get('password')
        new_password = self.cleaned_data.get('new_password')
        new_password_confirm = self.cleaned_data.get('new_password_confirm')
        validate_password(new_password)
        compare_passwords(new_password, new_password_confirm)
        if password == new_password:
            raise ValidationError(
                'Password and New Password cannot be equal', code='invalid'
            )

users/templates/users/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ user|title }} |
{% endblock %}

{% block content %}
    <div class="card mb-3 text-dark">
        <div class="card-header">
            <h5 class="card-title text-center">{{ user|title }}'s Account</h5>
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <i class="fa-solid fa-id-card"></i>
                    First Name: {{ user.first_name|title }}
                </li>
                <li class="list-group-item">
                    <i class="fa-solid fa-address-card"></i>
                    Last Name: {{ user.last_name|title }}
                </li>
                <li class="list-group-item">
                    <i class="fa-solid fa-user"></i>
                    Username: {{ user|title }}
                </li>
                <li class="list-group-item">
                    <i class="fa-solid fa-envelope"></i>
                    Email: {{ user.email }}
                </li>
            </ul>
        </div>
        <div class="card-footer">
            <a class="btn btn-warning" href="{% url 'users:update' %}">
                Edit Account
            </a>
            <a class="btn btn-warning" href="{% url 'users:update_password' %}">
                Change Password
            </a>
        </div>
    </div>
{% endblock %}

users/templates/users/forgot_password.html
{% extends 'base.html' %}

{% block title %}
    Forgot Password |
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-warning">Send</button>
    </form>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    Login |
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}

        {% for field in form %}
            <div class="mb-3">
                <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-warning">Login</button>
        <a class="btn btn-warning" href="{% url 'users:register' %}">Register New Account</a>
        <a class="btn btn-warning" href="{% url 'users:forgot_password' %}">Forgot my password</a>
    </form>
{% endblock %}

users/templates/users/logout.html
<form action="{% url 'users:logout' %}" method="POST">
    {% csrf_token %}

    <input type="submit" class="dropdown-item" value="Logout">
</form>

users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}
    Register |
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'users:register' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-warning">Register</button>
    </form>
{% endblock %}

users/templates/users/update.html
{% extends 'base.html' %}

{% block title %}
    Edit Account {{ request.user.username }} |
{% endblock %}

{% block content %}
    <form method="post"">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit Account" class="btn btn-warning">
    </form>
{% endblock %}

users/templates/users/update_password.html
{% extends 'base.html' %}

{% block title %}
    Update Password |
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'users:update_password' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-warning">Update Password</button>
    </form>
{% endblock %}