_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehicles.urls')),
    path('users/', include('users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('detail/me/', views.Detail.as_view(), name='detail'),
    path('update/me/', views.Update.as_view(), name='update'),
    path('update/password/', views.UpdatePassword.as_view(), name='update_password'),
    path('forgot-password/', views.ForgotPassword.as_view(), name='forgot_password')
]

vehicles/urls.py
from django.urls import path
from . import views
from rest_framework.routers import SimpleRouter

app_name = 'vehicles'

router = SimpleRouter()
router.register('vehicles/api/v1/brands', views.api.BrandViewSet, basename='api-v1-brands')
router.register('vehicles/api/v1/models', views.api.ModelViewSet, basename='api-v1-models')
router.register('vehicles/api/v1', views.api.VehiclesViewSet, basename='api-v1')

urlpatterns = [
    path('', views.site.redirect_to_home, name='redirect-to-home'),
    path('vehicles/home/', views.site.List.as_view(), name='list'),
    path('vehicles/detail/<int:pk>', views.site.Detail.as_view(), name='detail'),
    path('about/', views.site.About.as_view(), name='about'),
]

urlpatterns += router.urls

vehicles/models/abstract_model.py
from django.db import models
from vehicles.managers import AbstractModelManager


class AbstractModel(models.Model):
    objects = AbstractModelManager()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

vehicles/models/brand.py
from vehicles.models.abstract_model import AbstractModel
from django.db import models


class Brand(AbstractModel):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

vehicles/models/image.py
from django.db import models
from vehicles.models import Vehicle
from vehicles.utils.functions import resize_image, remove_image


class Image(models.Model):
    image = models.ImageField(upload_to='vehicles/images/%Y/%m/%d', blank=True, null=True)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.image.name

    def __update(self):
        if self.id is not None:
            old_image = Image.objects.get(id=self.id)
            if self.image != old_image.image:
                remove_image(old_image.image)

    def save(self, *args, **kwargs):
        self.__update()
        super().save(*args, **kwargs)
        if self.image:
            resize_image(self.image)

    def delete(self, *args, **kwargs):
        remove_image(self.image)
        super().delete(*args, **kwargs)

vehicles/models/model.py
from vehicles.models.abstract_model import AbstractModel
from vehicles.models import Brand
from django.db import models
from vehicles.utils.type import Type


class Model(AbstractModel):
    name = models.CharField(max_length=255, unique=True)
    type = models.CharField(max_length=255, choices=Type.choices, default=Type.CAR)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

vehicles/models/vehicle.py
from vehicles.models import AbstractModel
from vehicles.utils.color import Color
from vehicles.utils.fuel import Fuel
from vehicles.utils.engine import Engine
from vehicles.utils.engine_type import EngineType
from vehicles.models import Model
from django.db import models
from datetime import datetime
from django.core.exceptions import ValidationError

class Vehicle(AbstractModel):
    color = models.CharField(max_length=255, choices=Color.choices, default=Color.RED)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    mileage = models.FloatField(default=0)
    price = models.FloatField(default=0)
    year = models.IntegerField()
    is_new = models.BooleanField(default=True)
    fuel = models.CharField(max_length=255, choices=Fuel.choices, default=Fuel.GASOLINE)
    engine = models.CharField(max_length=255, choices=Engine.choices, default=Engine.I3_10)
    engine_type = models.CharField(max_length=255, choices=EngineType.choices, default=EngineType.ASPIRATED)
    gears = models.IntegerField()
    automatic_transmission = models.BooleanField(default=False)
    description = models.TextField()

    def __str__(self):
        return self.model.name

    def clean(self):
        if not (len(str(self.year)) == 4 and 0 < self.year <= int(datetime.now().strftime("%Y"))):
            raise ValidationError({'year': 'Invalid year'})
        return super().clean()

vehicles/templates/vehicles/partials/carousel_images.html
<div id="carouselExampleIndicators{{ vehicle.id }}" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        {% for image in vehicle.image_set.all %}
                <button type="button" data-bs-target="#carouselExampleIndicators{{ vehicle.id }}" data-bs-slide-to=
                        "{{ forloop.counter0 }}"
                        {% if forloop.first %}class="active" aria-current="true"{% endif %}
                        aria-label="Slide {{ forloop.counter0 }}">
                </button>
        {% endfor %}
    </div>
    <div class="carousel-inner">
        {% for image in vehicle.image_set.all %}
            {% if image.image %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <a href="{% url 'vehicles:detail' vehicle.id %}"><img src="{{ image.image.url }}" class="d-block
                    w-100" alt="..."></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators{{ vehicle.id }}"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators{{ vehicle.id }}"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

vehicles/templates/vehicles/partials/pagination.html
{% if is_paginated %}
    <nav aria-label="pagination">
        <ul class="pagination g-4">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page=1&
search={{ request.GET.search }}&type={{ request.GET.type }}">&laquo;</a>
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&
search={{ request.GET.search }}&type={{ request.GET.type }}">&lsaquo;</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ num }}&
search={{ request.GET.search }}&type={{ request.GET.type }}">{{ num }}</a>
                    </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}&
search={{ request.GET.search }}&type={{ request.GET.type }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="page-link page-item" href="?page={{ page_obj.next_page_number }}&
search={{ request.GET.search }}&type={{ request.GET.type }}">&rsaquo;</a>
                <a class="page-link page-item" href="?page={{ page_obj.paginator.num_pages }}&
search={{ request.GET.search }}&type={{ request.GET.type }}">&raquo;</a>
            {% endif %}
        </ul>
    </nav>

    <style>
        .page-item.active .page-link {
            background-color: #ffc107;;
            border-color: #ffc107;;
        }

        .page-link {
            color: #ffc107;
        }

        .pagination {
            margin-top: 0.5rem;
        }
    </style>
{% endif %}